name = "scholz.Ruhr Theme"
licenselink = "https://github.com/ruhrscholz/scholz.ruhr/blob/master/LICENSE"
description = ""
homepage = "https://scholz.ruhr/"
tags = []
features = []
min_version = "0.113.0"

[author]
  name = "Merlin Scholz"
  homepage = "https://scholz.ruhr"
